### ISSUE TITLE
项目拉下来不能构建。

### ISSUE THREAD

**Issue by chinnsenn** [Panl/Gank.io#1]
缺少文件

> Error:(8, 0) /Users/leoonly/Documents/Android/Gank.io/config.properties (No such file or directory)
> <a href="openFile:/Users/leoonly/Documents/Android/Gank.io/app/build.gradle">Open File</a>

**Properties properties = new Properties()
properties.load(project.rootProject.file('config.properties').newDataInputStream())**

**Comment by Panl** [comment]
因为这个文件里存放的是签名信息，所以没有放在版本控制里，你可以自己新建Config.properties文件
