### ISSUE TITLE
写得真的不错

### ISSUE THREAD

**Issue by DyncLang** [Panl/Gank.io#3]
这一久正好在看MVP，看到Panl写的恍然大悟，而且特别取巧，比如在`IBaseView`中`init()`. 使用泛型在BasePresenter去调用。虽然不直白，但是能够想到你写的想法。

**Comment by Panl** [comment]
谢谢

**Comment by DyncLang** [comment]
有机会能够多向你多学习一下。哈哈。

**Comment by Panl** [comment]
learn from each other
