### ISSUE TITLE
友盟依赖的小小问题

### ISSUE THREAD

**Issue by youxiachai** [Panl/Gank.io#4]
#1 这里提到了部分问题。。。这个问题还好

但是有个umeng的问题。。我就很费解了。。用了Placeholders，然而漏了debug。。。

string那头把key是删掉了，为啥只删key？不把整个友盟依赖改掉。。。这样更省事吧？

不过，应该是没删干净吧？

或者这个是作者留个大家的考验？

连简单修改都不会，还看什么源码。。。

**Comment by Panl** [comment]
what are you saying？
